# /home/brijeshdhaker/.jupysql/connections.ini
[mysql]
drivername = mysql+pymysql
username = mysqladmin
password = paSSW0rd
host = mysqlserver.sandbox.net
port = 3306
database = SANDBOXDB

[postgres]
drivername = postgresql
username = postgres
password = paSSW0rd
host = postgresql.sandbox.net
port = 5432
database = sandboxdb
