#
# docker compose -f docker-compose.yml up -d
# docker compose -f docker-compose.yml down
#
# docker compose -f docker-compose.yml up -d minio
# docker compose -f docker-compose.yml down minio
#
# docker compose -f docker-compose.yml up -d mysqlserver
# docker compose -f docker-compose.yml down mysqlserver
#
#
# docker volume create --name sandbox_minio_data --opt type=none --opt device=/apps/sandbox/minio --opt o=bind
# docker pull minio/minio:RELEASE.2024-07-29T22-14-52Z
#
#
# docker compose -f docker-compose.yml up -d minio
# docker compose -f docker-compose.yml down minio
#
#
# Use root/paSSW0rd user/password credentials
#
# docker volume create --name sandbox_apps_path --opt type=none --opt device=/apps --opt o=bind
# docker volume create --name sandbox_mysql_data --opt type=none --opt device=/apps/sandbox/mysql/data --opt o=bind
#
# docker compose -f docker-compose.yml up -d mysqlserver
# docker compose -f docker-compose.yml down mysqlserver
#
# docker exec -it mysqlserver mysql --user=root --password=paSSW0rd --host=localhost
# docker exec -it mysqlserver mysql --user=root --password=paSSW0rd --host=mysqlserver.sandbox.net --database=SANDBOXDB
#
#
# docker compose -f docker-compose.yml up -d postgres
# docker compose -f docker-compose.yml down postgres
#
# docker exec -it postgresql psql -h postgresql.sandbox.net -U postgres -d SANDBOXDB
# docker exec -it postgresql psql -h postgresql.sandbox.net -U postgres -d SANDBOXDB
#

# Use postgres/example user/password credentials
# psql -h postgres.sandbox.net -U $POSTGRES_USER -d $POSTGRES_DB
# psql -h postgres.sandbox.net -U $POSTGRES_USER -d $POSTGRES_DB -W $POSTGRES_ADMIN_PASSWORD
#
# CREATE EXTENSION vector;
# SELECT * FROM pg_extension;
# CREATE TABLE items (id bigserial PRIMARY KEY, embedding vector(3));
# INSERT INTO items (embedding) VALUES ('[1,2,3]'), ('[4,5,6]');
# SELECT * FROM items ORDER BY embedding <-> '[3,1,2]' LIMIT 5;
#

#
# docker compose -f docker-compose.yml up -d zookeeper kafkabroker schemaregistry
# docker compose -f docker-compose.yml down zookeeper kafkabroker schemaregistry
#
# docker volume create --name sandbox_security_secrets --opt type=none --opt device=/apps/security/ssl --opt o=bind
# docker volume create --name sandbox_zookeeper_data --opt type=none --opt device=/apps/sandbox/zookeeper/data --opt o=bind
# docker volume create --name sandbox_zookeeper_log --opt type=none --opt device=/apps/sandbox/zookeeper/log --opt o=bind
# docker volume create --name sandbox_kafka_data --opt type=none --opt device=/apps/sandbox/kafka/data --opt o=bind
# docker volume create --name sandbox_kafka_log --opt type=none --opt device=/apps/sandbox/kafka/log --opt o=bind
# docker volume create --name sandbox_schema_registry_data --opt type=none --opt device=/apps/sandbox/schemaregistry/data --opt o=bind
# docker volume create --name sandbox_schema_registry_log --opt type=none --opt device=/apps/sandbox/schemaregistry/log --opt o=bind
#

# include:
#  - path: ./docker-minio.yml
#  - path: ./docker-mysqlserver.yml
#  - path: ./docker-postgres.yml

#
services:
  
  #
  devcontainer:
    image: mcr.microsoft.com/devcontainers/miniconda:1-3
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    volumes:
      - .:/workspace/bd-notebooks-module:cached
      - ${HOME}/.m2:/home/vscode/.m2
      - ${HOME}/.ivy2:/home/vscode/.ivy2
      - sandbox_apps_path:/apps
    depends_on:
      - minio
    extra_hosts:
      - docker.sandbox.net:172.18.0.1
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: "sandbox.net"
    # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  ## Zookeeper Server
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.2
    hostname: zookeeper.sandbox.net
    container_name: zookeeper
    healthcheck:
      test: curl -f http://zookeeper.sandbox.net:8080/commands || exit 1
      retries: 20
      interval: 10s
    ports:
      - "2181:2181"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_security_secrets:/etc/zookeeper/secrets
      - sandbox_zookeeper_data:/var/lib/zookeeper/data
      - sandbox_zookeeper_log:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_UNSIGNED: "true"
    extra_hosts:
      - "docker.sandbox.net:172.18.0.1"

  ## Confluent Kafka Server
  kafkabroker:
    image: confluentinc/cp-kafka:7.5.2
    hostname: kafkabroker.sandbox.net
    container_name: kafkabroker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    healthcheck:
      test: nc -vz kafkabroker.sandbox.net 19092 || exit 1
      retries: 20
      interval: 10s
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_security_secrets:/etc/kafka/secrets
      - sandbox_kafka_data:/var/lib/kafka/data
      - sandbox_kafka_log:/var/lib/kafka/log
    environment:
      KAFKA_BROKER_ID: "1"
      #KAFKA_BROKER_RACK: "R1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper.sandbox.net:2181
      KAFKA_ADVERTISED_HOST_NAME: docker.sandbox.net
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafkabroker.sandbox.net:19092,EXTERNAL://kafkabroker.sandbox.net:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schemaregistry.sandbox.net:8081
      KAFKA_CREATE_TOPICS: "simple-topic:1:1"
      # HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $2}'"
    extra_hosts:
      - "docker.sandbox.net:172.18.0.1"

  ## schemaregistry
  schemaregistry:
    image: confluentinc/cp-schemaregistry:7.5.2
    hostname: schemaregistry.sandbox.net
    container_name: schemaregistry
    depends_on:
      - zookeeper
      - kafkabroker
    healthcheck:
      test: curl -f http://schemaregistry.sandbox.net:8081 || exit 1
      retries: 20
      interval: 10s
    ports:
      - "8081:8081"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_security_secrets:/etc/schemaregistry/secrets
      - sandbox_schema_registry_data:/var/lib/schemaregistry/data
      - sandbox_schema_registry_log:/var/lib/schemaregistry/log
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schemaregistry.sandbox.net
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafkabroker.sandbox.net:19092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO
    extra_hosts:
      - "docker.sandbox.net:172.18.0.1"

  ## minio
  minio:
    image: minio/minio:RELEASE.2024-07-29T22-14-52Z
    hostname: minio.sandbox.net
    container_name: minio
    healthcheck:
      test: echo minio.sandbox.net || exit 1
      retries: 20
      interval: 10s
    networks:
      default:
        aliases:
          - warehouse-hadoop.minio
          - warehouse-flink.minio
          - warehouse-rest.minio
          - warehouse-data.minio
          - warehouse-demo.minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
      - MINIO_ADDRESS=0.0.0.0:9010
      - MINIO_CONSOLE_ADDRESS=0.0.0.0:9011
      # - MINIO_ACCESS_KEY_FILE=/apps/security/keys/minio_access_key
      # - MINIO_SECRET_KEY_FILE=/apps/security/keys/minio_secret_key
      # - MINIO_ROOT_USER_FILE=/apps/security/keys/minio_root_user
      # - MINIO_ROOT_PASSWORD_FILE=/apps/security/keys/minio_root_password
    ports:
      - "9010:9010"
      - "9011:9011"
    command: ["server", "/data", "--console-address", ":9011"]
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_minio_data:/data
    extra_hosts:
      - "docker.sandbox.net:172.18.0.1"

  ## Mysql Server
  mysqlserver:
    image: mysql:8.0.33
    container_name: mysqlserver
    hostname: mysqlserver.sandbox.net
    restart: always
    ports:
      - "3306:3306"
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    volumes:
      - sandbox_apps_path:/apps
      - sandbox_mysql_data:/var/lib/mysql
      - ./conf/mysql:/etc/mysql/conf.d
      - ./conf/mysql/init-setup.sh:/docker-entrypoint-initdb.d/init-setup.sh
    secrets:
      - mysql-root-password
    env_file:
      - ./conf/mysql/envvars
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=$$MYSQL_ADMIN_PASSWORD --execute \"SHOW DATABASES;\""
      # test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ADMIN_PASSWORD']
      timeout: 20s
      retries: 10
      interval: 10s
    extra_hosts:
      - "docker.sandbox.net:172.18.0.1"
      
  ## Postgres Server
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgresql
    hostname: postgresql.sandbox.net
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    ports:
      - "5432:5432"    
    volumes:
      # - sandbox_apps_path:/apps
      - /apps/sandbox/postgres/data:/var/lib/postgresql/data
      - ./conf/postgres/postgres.conf:/etc/postgresql/postgresql.conf
      #- ./conf/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
    secrets:
      - postgres-passwd    
    env_file:
      - ./conf/postgres/envvars
    extra_hosts:
      - "docker.sandbox.net:172.18.0.1"

  # #      
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  
## secrets
secrets:
  mysql-root-password:
    file: ./conf/mysql/password.txt
  postgres-passwd:
    file: ./conf/postgres/password.txt

## 
models:
  llama:
    model: ai/llama3.2:1B-Q8_0
    context_size: 2048
  embedding-model:
    model: ai/all-minilm-l6-v2-vllm


## Docker Volumes
volumes:
  #
  sandbox_apps_path:
    external: true
  #  
  sandbox_security_secrets:
    external: true
  #  
  sandbox_mysql_data:
    external: true
  #  
  sandbox_minio_data:
    external: true
  #
  sandbox_zookeeper_data:
    external: true
  sandbox_zookeeper_log:
    external: true
  #
  sandbox_kafka_data:
    external: true
  sandbox_kafka_log:
    external: true
  #
  sandbox_schema_registry_data:
    external: true
  sandbox_schema_registry_log:
    external: true

## Docker Networks
networks:
  default:
    external: true
    driver: bridge
    name: sandbox.net
